// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenRequest) Reset()         { *m = GenerateTokenRequest{} }
func (m *GenerateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenRequest) ProtoMessage()    {}
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_35b5bc3fa6679961, []int{0}
}
func (m *GenerateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenRequest.Unmarshal(m, b)
}
func (m *GenerateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenRequest.Merge(dst, src)
}
func (m *GenerateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenRequest.Size(m)
}
func (m *GenerateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenRequest proto.InternalMessageInfo

func (m *GenerateTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GenerateTokenRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type GenerateTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenResponse) Reset()         { *m = GenerateTokenResponse{} }
func (m *GenerateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenResponse) ProtoMessage()    {}
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_35b5bc3fa6679961, []int{1}
}
func (m *GenerateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenResponse.Unmarshal(m, b)
}
func (m *GenerateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenResponse.Merge(dst, src)
}
func (m *GenerateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenResponse.Size(m)
}
func (m *GenerateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenResponse proto.InternalMessageInfo

func (m *GenerateTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GenerateTokenResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ParseTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseTokenRequest) Reset()         { *m = ParseTokenRequest{} }
func (m *ParseTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ParseTokenRequest) ProtoMessage()    {}
func (*ParseTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_35b5bc3fa6679961, []int{2}
}
func (m *ParseTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseTokenRequest.Unmarshal(m, b)
}
func (m *ParseTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseTokenRequest.Marshal(b, m, deterministic)
}
func (dst *ParseTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseTokenRequest.Merge(dst, src)
}
func (m *ParseTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ParseTokenRequest.Size(m)
}
func (m *ParseTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseTokenRequest proto.InternalMessageInfo

func (m *ParseTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ParseTokenResponse struct {
	Claims               *Claims  `protobuf:"bytes,1,opt,name=Claims" json:"Claims,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseTokenResponse) Reset()         { *m = ParseTokenResponse{} }
func (m *ParseTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ParseTokenResponse) ProtoMessage()    {}
func (*ParseTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_35b5bc3fa6679961, []int{3}
}
func (m *ParseTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseTokenResponse.Unmarshal(m, b)
}
func (m *ParseTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseTokenResponse.Marshal(b, m, deterministic)
}
func (dst *ParseTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseTokenResponse.Merge(dst, src)
}
func (m *ParseTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ParseTokenResponse.Size(m)
}
func (m *ParseTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseTokenResponse proto.InternalMessageInfo

func (m *ParseTokenResponse) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *ParseTokenResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Claims struct {
	Exp                  int64    `protobuf:"varint,1,opt,name=Exp" json:"Exp,omitempty"`
	Iat                  int64    `protobuf:"varint,2,opt,name=Iat" json:"Iat,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_35b5bc3fa6679961, []int{4}
}
func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (dst *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(dst, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Claims) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *Claims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Claims) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateTokenRequest)(nil), "pb.GenerateTokenRequest")
	proto.RegisterType((*GenerateTokenResponse)(nil), "pb.GenerateTokenResponse")
	proto.RegisterType((*ParseTokenRequest)(nil), "pb.ParseTokenRequest")
	proto.RegisterType((*ParseTokenResponse)(nil), "pb.ParseTokenResponse")
	proto.RegisterType((*Claims)(nil), "pb.Claims")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for JWT service

type JWTClient interface {
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	ParseToken(ctx context.Context, in *ParseTokenRequest, opts ...grpc.CallOption) (*ParseTokenResponse, error)
}

type jWTClient struct {
	cc *grpc.ClientConn
}

func NewJWTClient(cc *grpc.ClientConn) JWTClient {
	return &jWTClient{cc}
}

func (c *jWTClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	out := new(GenerateTokenResponse)
	err := grpc.Invoke(ctx, "/pb.JWT/GenerateToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) ParseToken(ctx context.Context, in *ParseTokenRequest, opts ...grpc.CallOption) (*ParseTokenResponse, error) {
	out := new(ParseTokenResponse)
	err := grpc.Invoke(ctx, "/pb.JWT/ParseToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JWT service

type JWTServer interface {
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	ParseToken(context.Context, *ParseTokenRequest) (*ParseTokenResponse, error)
}

func RegisterJWTServer(s *grpc.Server, srv JWTServer) {
	s.RegisterService(&_JWT_serviceDesc, srv)
}

func _JWT_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JWT/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_ParseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).ParseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JWT/ParseToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).ParseToken(ctx, req.(*ParseTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JWT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.JWT",
	HandlerType: (*JWTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateToken",
			Handler:    _JWT_GenerateToken_Handler,
		},
		{
			MethodName: "ParseToken",
			Handler:    _JWT_ParseToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt.proto",
}

func init() { proto.RegisterFile("jwt.proto", fileDescriptor_jwt_35b5bc3fa6679961) }

var fileDescriptor_jwt_35b5bc3fa6679961 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0xdd, 0x5a, 0xe8, 0x88, 0xa0, 0x43, 0x2b, 0xb1, 0x27, 0xd9, 0x93, 0x5e, 0x72, 0xa8,
	0x67, 0x51, 0x90, 0x28, 0xf6, 0x24, 0x4b, 0xd1, 0xf3, 0x06, 0xe6, 0x50, 0x4d, 0xb3, 0xeb, 0xee,
	0x8a, 0x7e, 0x84, 0x1f, 0x2d, 0x3b, 0x49, 0x49, 0x9b, 0xe4, 0xf6, 0xf6, 0xcd, 0x9b, 0xf7, 0x32,
	0x2f, 0x30, 0xfd, 0xf8, 0x09, 0x99, 0x75, 0x26, 0x18, 0x1c, 0xd9, 0x42, 0x3e, 0xc0, 0xec, 0x99,
	0x2a, 0x72, 0x3a, 0xd0, 0xda, 0x7c, 0x52, 0xa5, 0xe8, 0xeb, 0x9b, 0x7c, 0xc0, 0x19, 0x1c, 0xe7,
	0x5b, 0xbd, 0x29, 0xd3, 0xe4, 0x2a, 0xb9, 0x9e, 0xaa, 0xfa, 0x81, 0x08, 0x63, 0x65, 0x4a, 0x4a,
	0x47, 0x4c, 0x32, 0x96, 0xf7, 0x30, 0xef, 0x38, 0x78, 0x6b, 0x2a, 0x4f, 0xd1, 0x82, 0x89, 0x9d,
	0x05, 0x3f, 0xf0, 0x0c, 0x44, 0xee, 0x5c, 0xe3, 0x10, 0xa1, 0xbc, 0x81, 0xf3, 0x57, 0xed, 0x7c,
	0x2f, 0xbf, 0xbf, 0x2c, 0x57, 0x80, 0xfb, 0xd2, 0x26, 0x48, 0xc2, 0xe4, 0xb1, 0xd4, 0x9b, 0xad,
	0x67, 0xf1, 0xc9, 0x12, 0x32, 0x5b, 0x64, 0x35, 0xa3, 0x9a, 0x49, 0x8c, 0xa5, 0x36, 0x96, 0x9c,
	0x93, 0x6f, 0xb0, 0x37, 0xcb, 0x7f, 0x2d, 0x2f, 0x0b, 0x15, 0x61, 0x64, 0x5e, 0x74, 0x60, 0xb5,
	0x50, 0x11, 0xb6, 0x7d, 0x88, 0xa1, 0x3e, 0xc6, 0x6d, 0x1f, 0xcb, 0xbf, 0x04, 0xc4, 0xea, 0x7d,
	0x8d, 0x4f, 0x70, 0x7a, 0xd0, 0x0b, 0xa6, 0xf1, 0xb3, 0x86, 0xca, 0x5e, 0x5c, 0x0e, 0x4c, 0xea,
	0xdb, 0xe4, 0x11, 0xde, 0x01, 0xb4, 0x37, 0xe3, 0x3c, 0x4a, 0x7b, 0x75, 0x2d, 0x2e, 0xba, 0xf4,
	0x6e, 0xbd, 0x98, 0xf0, 0xbf, 0xbe, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xbe, 0xef, 0xa6,
	0xf8, 0x01, 0x00, 0x00,
}
