// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenRequest) Reset()         { *m = GenerateTokenRequest{} }
func (m *GenerateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenRequest) ProtoMessage()    {}
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_076016844287edc8, []int{0}
}
func (m *GenerateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenRequest.Unmarshal(m, b)
}
func (m *GenerateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenRequest.Merge(dst, src)
}
func (m *GenerateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenRequest.Size(m)
}
func (m *GenerateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenRequest proto.InternalMessageInfo

func (m *GenerateTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GenerateTokenRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type GenerateTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenResponse) Reset()         { *m = GenerateTokenResponse{} }
func (m *GenerateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenResponse) ProtoMessage()    {}
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_076016844287edc8, []int{1}
}
func (m *GenerateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenResponse.Unmarshal(m, b)
}
func (m *GenerateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenResponse.Merge(dst, src)
}
func (m *GenerateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenResponse.Size(m)
}
func (m *GenerateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenResponse proto.InternalMessageInfo

func (m *GenerateTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GenerateTokenResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ValidateTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenRequest) Reset()         { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()    {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_076016844287edc8, []int{2}
}
func (m *ValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenRequest.Unmarshal(m, b)
}
func (m *ValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenRequest.Marshal(b, m, deterministic)
}
func (dst *ValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenRequest.Merge(dst, src)
}
func (m *ValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenRequest.Size(m)
}
func (m *ValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenRequest proto.InternalMessageInfo

func (m *ValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	Claims               map[string]*any.Any `protobuf:"bytes,1,rep,name=claims" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Err                  string              `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateTokenResponse) Reset()         { *m = ValidateTokenResponse{} }
func (m *ValidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResponse) ProtoMessage()    {}
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_076016844287edc8, []int{3}
}
func (m *ValidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResponse.Unmarshal(m, b)
}
func (m *ValidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResponse.Marshal(b, m, deterministic)
}
func (dst *ValidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResponse.Merge(dst, src)
}
func (m *ValidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResponse.Size(m)
}
func (m *ValidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResponse proto.InternalMessageInfo

func (m *ValidateTokenResponse) GetClaims() map[string]*any.Any {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *ValidateTokenResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateTokenRequest)(nil), "pb.GenerateTokenRequest")
	proto.RegisterType((*GenerateTokenResponse)(nil), "pb.GenerateTokenResponse")
	proto.RegisterType((*ValidateTokenRequest)(nil), "pb.ValidateTokenRequest")
	proto.RegisterType((*ValidateTokenResponse)(nil), "pb.ValidateTokenResponse")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pb.ValidateTokenResponse.ClaimsEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for JWT service

type JWTClient interface {
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type jWTClient struct {
	cc *grpc.ClientConn
}

func NewJWTClient(cc *grpc.ClientConn) JWTClient {
	return &jWTClient{cc}
}

func (c *jWTClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	out := new(GenerateTokenResponse)
	err := grpc.Invoke(ctx, "/pb.JWT/GenerateToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := grpc.Invoke(ctx, "/pb.JWT/ValidateToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JWT service

type JWTServer interface {
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
}

func RegisterJWTServer(s *grpc.Server, srv JWTServer) {
	s.RegisterService(&_JWT_serviceDesc, srv)
}

func _JWT_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JWT/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JWT/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JWT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.JWT",
	HandlerType: (*JWTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateToken",
			Handler:    _JWT_GenerateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _JWT_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt.proto",
}

func init() { proto.RegisterFile("jwt.proto", fileDescriptor_jwt_076016844287edc8) }

var fileDescriptor_jwt_076016844287edc8 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0x97, 0xed, 0xbf, 0xc1, 0xce, 0xf8, 0x83, 0x84, 0x0e, 0xba, 0x5d, 0x8d, 0x80, 0x30,
	0x44, 0x32, 0x98, 0x37, 0x22, 0x88, 0x8a, 0x4c, 0xc1, 0x1b, 0xa1, 0x0c, 0xbd, 0x4e, 0xf5, 0x38,
	0xea, 0xb2, 0xa4, 0xa6, 0xad, 0xd2, 0x07, 0xf1, 0x61, 0x7c, 0x3b, 0x49, 0xd2, 0xa1, 0x9b, 0xb9,
	0x3b, 0x39, 0xe7, 0x3b, 0xbf, 0x7e, 0xe7, 0x2b, 0xf4, 0x5f, 0x3f, 0x4a, 0x9e, 0x1b, 0x5d, 0x6a,
	0xda, 0xce, 0xd3, 0xf1, 0x68, 0xa5, 0xf5, 0x4a, 0xe2, 0xcc, 0x75, 0xd2, 0xea, 0x65, 0x26, 0x54,
	0xed, 0xc7, 0xec, 0x12, 0xa2, 0x5b, 0x54, 0x68, 0x44, 0x89, 0x4b, 0xbd, 0x46, 0x95, 0xe0, 0x5b,
	0x85, 0x45, 0x49, 0x23, 0xe8, 0x2e, 0x36, 0x22, 0x93, 0x31, 0x99, 0x90, 0x69, 0x3f, 0xf1, 0x0f,
	0x4a, 0xe1, 0x5f, 0xa2, 0x25, 0xc6, 0x6d, 0xd7, 0x74, 0x35, 0xbb, 0x80, 0xe1, 0x1e, 0xa1, 0xc8,
	0xb5, 0x2a, 0xd0, 0x22, 0x5c, 0x63, 0x8b, 0x70, 0x0f, 0x7a, 0x00, 0x9d, 0x85, 0x31, 0x0d, 0xc1,
	0x96, 0xec, 0x18, 0xa2, 0x07, 0x21, 0xb3, 0xe7, 0x80, 0x85, 0xbf, 0xfb, 0xec, 0x8b, 0xc0, 0x70,
	0x4f, 0xde, 0x7c, 0xef, 0x1c, 0x7a, 0x4f, 0x52, 0x64, 0x9b, 0x22, 0x26, 0x93, 0xce, 0x74, 0x30,
	0x3f, 0xe4, 0x79, 0xca, 0x83, 0x52, 0x7e, 0xed, 0x74, 0x0b, 0x55, 0x9a, 0x3a, 0x69, 0x96, 0xac,
	0x31, 0xfc, 0x31, 0x86, 0xc6, 0x8c, 0xef, 0x61, 0xf0, 0x4b, 0x68, 0x05, 0x6b, 0xac, 0x1b, 0x37,
	0xb6, 0xa4, 0x47, 0xd0, 0x7d, 0x17, 0xb2, 0xf2, 0x79, 0x0c, 0xe6, 0x11, 0xf7, 0x39, 0xf3, 0x6d,
	0xce, 0xfc, 0x4a, 0xd5, 0x89, 0x97, 0x9c, 0xb5, 0x4f, 0xc9, 0xfc, 0x93, 0x40, 0xe7, 0xee, 0x71,
	0x49, 0x6f, 0xe0, 0xff, 0x4e, 0x64, 0x34, 0xb6, 0x56, 0x43, 0xff, 0x61, 0x3c, 0x0a, 0x4c, 0xfc,
	0x11, 0xac, 0x65, 0x39, 0x3b, 0xf7, 0x79, 0x4e, 0x28, 0x4c, 0xcf, 0x09, 0x86, 0xc1, 0x5a, 0x69,
	0xcf, 0x19, 0x3e, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xc8, 0x6b, 0x46, 0x37, 0x02, 0x00,
	0x00,
}
