version: '3.6'
services:

  apigateway:
    build:
      context: ./apigateway
    ports:
      - 8089:8089

  jwtauth:
    build:
      context: ./jwtauth
    ports:
      - 8087:8087
      - 8088:8088

  movies:
    build:
      context: ./movies
    ports:
      - 8081:8081
      - 8082:8082
    command: ["/server", "--dbhost", "cockroach"]
    restart: always
    depends_on:
      - cockroach

  users:
    build:
      context: ./users
    ports:
      - 8083:8083
      - 8084:8084
    command: ["/server", "--dbhost", "cockroach"]
    restart: always
    depends_on:
      - cockroach

  vault:
    build:
      context: ./vault
    ports:
      - 8085:8085
      - 8086:8086

  cockroach:
    image: cockroachdb/cockroach:v2.0.3
    ports:
      - 9080:8080
      - 26257:26257
    command: ["start", "--insecure"]

  cockroach-init:
    image: cockroachdb/cockroach:v2.0.3
    entrypoint: ["bash", "/cockroach/init.sh"]
    volumes:
      - ./database_init.sh:/cockroach/init.sh
    depends_on:
      - cockroach

  jaegger:
     image: jaegertracing/all-in-one:1.5.0
     ports:
       - 5775:5775/udp
       - 6831:6831/udp
       - 6832:6832/udp
       - 5778:5778
       - 16686:16686
       - 14268:14268
       - 9411:9411