// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password" json:"Password,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{0}
}
func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (dst *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(dst, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NewUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type NewUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{1}
}
func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (dst *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(dst, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

func (m *NewUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewUserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetUserByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailRequest) Reset()         { *m = GetUserByEmailRequest{} }
func (m *GetUserByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailRequest) ProtoMessage()    {}
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{2}
}
func (m *GetUserByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailRequest.Unmarshal(m, b)
}
func (m *GetUserByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailRequest.Merge(dst, src)
}
func (m *GetUserByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailRequest.Size(m)
}
func (m *GetUserByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailRequest proto.InternalMessageInfo

func (m *GetUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserByEmailResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailResponse) Reset()         { *m = GetUserByEmailResponse{} }
func (m *GetUserByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailResponse) ProtoMessage()    {}
func (*GetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{3}
}
func (m *GetUserByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailResponse.Unmarshal(m, b)
}
func (m *GetUserByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailResponse.Merge(dst, src)
}
func (m *GetUserByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailResponse.Size(m)
}
func (m *GetUserByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailResponse proto.InternalMessageInfo

func (m *GetUserByEmailResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserByEmailResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{4}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type ChangePasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,2,opt,name=CurrentPassword" json:"CurrentPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=NewPassword" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{5}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(dst, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{6}
}
func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(dst, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangePasswordResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{7}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_9aedab4b7a4a1006, []int{8}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserRequest)(nil), "pb.NewUserRequest")
	proto.RegisterType((*NewUserResponse)(nil), "pb.NewUserResponse")
	proto.RegisterType((*GetUserByEmailRequest)(nil), "pb.GetUserByEmailRequest")
	proto.RegisterType((*GetUserByEmailResponse)(nil), "pb.GetUserByEmailResponse")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*ChangePasswordRequest)(nil), "pb.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "pb.ChangePasswordResponse")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	out := new(NewUserResponse)
	err := grpc.Invoke(ctx, "/pb.Users/NewUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error) {
	out := new(GetUserByEmailResponse)
	err := grpc.Invoke(ctx, "/pb.Users/GetUserByEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := grpc.Invoke(ctx, "/pb.Users/ChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/pb.Users/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	NewUser(context.Context, *NewUserRequest) (*NewUserResponse, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserByEmailResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).NewUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUser",
			Handler:    _Users_NewUser_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _Users_GetUserByEmail_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Users_ChangePassword_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Users_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_users_9aedab4b7a4a1006) }

var fileDescriptor_users_9aedab4b7a4a1006 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcf, 0xaf, 0xd2, 0x40,
	0x10, 0x7e, 0xfd, 0xe5, 0xc3, 0xe1, 0xc9, 0x7b, 0x8e, 0xef, 0x91, 0xda, 0x78, 0x20, 0x7b, 0xe2,
	0x62, 0x0f, 0xe0, 0x1f, 0x60, 0x44, 0xa2, 0x24, 0x84, 0x98, 0xaa, 0x27, 0x4f, 0x05, 0x46, 0x20,
	0x42, 0x5b, 0x77, 0xdb, 0x10, 0xce, 0x26, 0xfe, 0xdd, 0x66, 0x77, 0xbb, 0x4d, 0x8b, 0x85, 0xdb,
	0xce, 0x37, 0xb3, 0xf3, 0x7d, 0xfb, 0xcd, 0xb4, 0xd0, 0x2d, 0x04, 0x71, 0x11, 0x66, 0x3c, 0xcd,
	0x53, 0xb4, 0xb3, 0x25, 0xfb, 0x6b, 0x41, 0x6f, 0x41, 0xc7, 0xef, 0x82, 0x78, 0x44, 0xbf, 0x0b,
	0x12, 0x39, 0x22, 0xb8, 0x8b, 0xf8, 0x40, 0xbe, 0x35, 0xb0, 0x86, 0xcf, 0x23, 0x75, 0xc6, 0x00,
	0x3a, 0xf3, 0x58, 0xe4, 0x0a, 0xb7, 0x15, 0x5e, 0xc5, 0xf8, 0x08, 0xde, 0xf4, 0x10, 0xef, 0xf6,
	0xbe, 0xa3, 0x12, 0x3a, 0x90, 0x37, 0xbe, 0xc4, 0x42, 0x1c, 0x53, 0xbe, 0xf6, 0x5d, 0x7d, 0xc3,
	0xc4, 0x92, 0x21, 0x4a, 0xf7, 0xe4, 0x7b, 0x9a, 0x41, 0x9e, 0xd9, 0x18, 0xee, 0x2b, 0x1d, 0x22,
	0x4b, 0x13, 0x41, 0xd8, 0x03, 0x7b, 0xb6, 0x2e, 0x65, 0xd8, 0xb3, 0x35, 0x3e, 0x80, 0x33, 0xe5,
	0xbc, 0xe4, 0x97, 0x47, 0xf6, 0x16, 0x9e, 0x3e, 0x51, 0x2e, 0x2f, 0x7d, 0x38, 0x29, 0x5a, 0xf3,
	0x86, 0x4a, 0x93, 0x55, 0xd3, 0xc4, 0x3e, 0x43, 0xff, 0xbc, 0xbc, 0xa4, 0x7a, 0x03, 0xae, 0x74,
	0x46, 0x95, 0x77, 0x47, 0x9d, 0x30, 0x5b, 0x86, 0x4a, 0x8a, 0x42, 0x5b, 0x88, 0x33, 0x70, 0x65,
	0xfe, 0x3f, 0x89, 0xc6, 0x3b, 0xfb, 0x82, 0x77, 0xce, 0x25, 0xef, 0xdc, 0xba, 0x77, 0x6d, 0xfe,
	0x9c, 0xe0, 0x69, 0xb2, 0x8d, 0x93, 0x0d, 0x19, 0x17, 0xaf, 0x3e, 0x15, 0x87, 0x70, 0x3f, 0x29,
	0x38, 0xa7, 0x24, 0xaf, 0xa6, 0xa0, 0x35, 0x9d, 0xc3, 0x38, 0x80, 0xee, 0x82, 0x8e, 0x55, 0x95,
	0x56, 0x58, 0x87, 0xd8, 0x47, 0xe8, 0x9f, 0x53, 0x97, 0xb6, 0xf9, 0x70, 0xfb, 0xb5, 0x58, 0xad,
	0x48, 0x08, 0xc5, 0xde, 0x89, 0x4c, 0xd8, 0x62, 0xd9, 0x7b, 0xb8, 0x9b, 0xa7, 0x9b, 0x5d, 0x72,
	0x5d, 0x77, 0x7d, 0x6d, 0xec, 0xe6, 0xda, 0xb0, 0x1f, 0xf0, 0xa2, 0xec, 0x50, 0xd2, 0x3f, 0x82,
	0xf7, 0x2d, 0xfd, 0x45, 0x89, 0x69, 0xa1, 0x02, 0x64, 0x70, 0x17, 0xd1, 0x4f, 0x4e, 0x62, 0xab,
	0x93, 0xba, 0x4d, 0x03, 0x33, 0xf2, 0x9c, 0x4a, 0xde, 0xe8, 0x8f, 0x0d, 0x9e, 0x1c, 0xa9, 0xc0,
	0x77, 0x70, 0x5b, 0x6e, 0x22, 0xa2, 0x5c, 0x84, 0xe6, 0xe7, 0x11, 0xbc, 0x6a, 0x60, 0x5a, 0x09,
	0xbb, 0xc1, 0x19, 0xf4, 0x9a, 0xbb, 0x85, 0xaf, 0x65, 0x61, 0xeb, 0x7a, 0x06, 0x41, 0x5b, 0xaa,
	0xde, 0xaa, 0xe9, 0xb7, 0x6e, 0xd5, 0x3a, 0x7e, 0xdd, 0xaa, 0x7d, 0x3c, 0xec, 0x06, 0x43, 0xf0,
	0x94, 0x65, 0xf8, 0x20, 0xcb, 0xea, 0xfe, 0x07, 0x2f, 0x6b, 0x88, 0xa9, 0x5f, 0x3e, 0x53, 0x7f,
	0x86, 0xf1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x86, 0x3c, 0x20, 0x28, 0x04, 0x00, 0x00,
}
