// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movies.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMoviesResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMoviesResponse) Reset()         { *m = GetMoviesResponse{} }
func (m *GetMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMoviesResponse) ProtoMessage()    {}
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{0}
}
func (m *GetMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMoviesResponse.Unmarshal(m, b)
}
func (m *GetMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMoviesResponse.Marshal(b, m, deterministic)
}
func (dst *GetMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMoviesResponse.Merge(dst, src)
}
func (m *GetMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMoviesResponse.Size(m)
}
func (m *GetMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMoviesResponse proto.InternalMessageInfo

func (m *GetMoviesResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func (m *GetMoviesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Movie struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Director             []*Director          `protobuf:"bytes,3,rep,name=director" json:"director,omitempty"`
	Year                 string               `protobuf:"bytes,4,opt,name=year" json:"year,omitempty"`
	Createdby            string               `protobuf:"bytes,5,opt,name=createdby" json:"createdby,omitempty"`
	Createdon            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdon" json:"createdon,omitempty"`
	Updatedby            string               `protobuf:"bytes,7,opt,name=updatedby" json:"updatedby,omitempty"`
	Updatedon            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedon" json:"updatedon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{1}
}
func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (dst *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(dst, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetDirector() []*Director {
	if m != nil {
		return m.Director
	}
	return nil
}

func (m *Movie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Movie) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

func (m *Movie) GetCreatedon() *timestamp.Timestamp {
	if m != nil {
		return m.Createdon
	}
	return nil
}

func (m *Movie) GetUpdatedby() string {
	if m != nil {
		return m.Updatedby
	}
	return ""
}

func (m *Movie) GetUpdatedon() *timestamp.Timestamp {
	if m != nil {
		return m.Updatedon
	}
	return nil
}

type Director struct {
	Director             string   `protobuf:"bytes,1,opt,name=director" json:"director,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Director) Reset()         { *m = Director{} }
func (m *Director) String() string { return proto.CompactTextString(m) }
func (*Director) ProtoMessage()    {}
func (*Director) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{2}
}
func (m *Director) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Director.Unmarshal(m, b)
}
func (m *Director) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Director.Marshal(b, m, deterministic)
}
func (dst *Director) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Director.Merge(dst, src)
}
func (m *Director) XXX_Size() int {
	return xxx_messageInfo_Director.Size(m)
}
func (m *Director) XXX_DiscardUnknown() {
	xxx_messageInfo_Director.DiscardUnknown(m)
}

var xxx_messageInfo_Director proto.InternalMessageInfo

func (m *Director) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

type GetMovieByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieByIdRequest) Reset()         { *m = GetMovieByIdRequest{} }
func (m *GetMovieByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieByIdRequest) ProtoMessage()    {}
func (*GetMovieByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{3}
}
func (m *GetMovieByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieByIdRequest.Unmarshal(m, b)
}
func (m *GetMovieByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetMovieByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieByIdRequest.Merge(dst, src)
}
func (m *GetMovieByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieByIdRequest.Size(m)
}
func (m *GetMovieByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieByIdRequest proto.InternalMessageInfo

func (m *GetMovieByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetMovieByIdResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie" json:"movie,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieByIdResponse) Reset()         { *m = GetMovieByIdResponse{} }
func (m *GetMovieByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieByIdResponse) ProtoMessage()    {}
func (*GetMovieByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{4}
}
func (m *GetMovieByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieByIdResponse.Unmarshal(m, b)
}
func (m *GetMovieByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieByIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetMovieByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieByIdResponse.Merge(dst, src)
}
func (m *GetMovieByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieByIdResponse.Size(m)
}
func (m *GetMovieByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieByIdResponse proto.InternalMessageInfo

func (m *GetMovieByIdResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

func (m *GetMovieByIdResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type NewMovieRequest struct {
	Title                string      `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Director             []*Director `protobuf:"bytes,2,rep,name=director" json:"director,omitempty"`
	Year                 string      `protobuf:"bytes,3,opt,name=year" json:"year,omitempty"`
	Createdby            string      `protobuf:"bytes,4,opt,name=createdby" json:"createdby,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewMovieRequest) Reset()         { *m = NewMovieRequest{} }
func (m *NewMovieRequest) String() string { return proto.CompactTextString(m) }
func (*NewMovieRequest) ProtoMessage()    {}
func (*NewMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{5}
}
func (m *NewMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMovieRequest.Unmarshal(m, b)
}
func (m *NewMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMovieRequest.Marshal(b, m, deterministic)
}
func (dst *NewMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMovieRequest.Merge(dst, src)
}
func (m *NewMovieRequest) XXX_Size() int {
	return xxx_messageInfo_NewMovieRequest.Size(m)
}
func (m *NewMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMovieRequest proto.InternalMessageInfo

func (m *NewMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewMovieRequest) GetDirector() []*Director {
	if m != nil {
		return m.Director
	}
	return nil
}

func (m *NewMovieRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *NewMovieRequest) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

type NewMovieResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMovieResponse) Reset()         { *m = NewMovieResponse{} }
func (m *NewMovieResponse) String() string { return proto.CompactTextString(m) }
func (*NewMovieResponse) ProtoMessage()    {}
func (*NewMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{6}
}
func (m *NewMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMovieResponse.Unmarshal(m, b)
}
func (m *NewMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMovieResponse.Marshal(b, m, deterministic)
}
func (dst *NewMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMovieResponse.Merge(dst, src)
}
func (m *NewMovieResponse) XXX_Size() int {
	return xxx_messageInfo_NewMovieResponse.Size(m)
}
func (m *NewMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewMovieResponse proto.InternalMessageInfo

func (m *NewMovieResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewMovieResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteMovieRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{7}
}
func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(dst, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMovieResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{8}
}
func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(dst, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UpdateMovieRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string      `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Director             []*Director `protobuf:"bytes,3,rep,name=director" json:"director,omitempty"`
	Year                 string      `protobuf:"bytes,4,opt,name=year" json:"year,omitempty"`
	Createdby            string      `protobuf:"bytes,5,opt,name=createdby" json:"createdby,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateMovieRequest) Reset()         { *m = UpdateMovieRequest{} }
func (m *UpdateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMovieRequest) ProtoMessage()    {}
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{9}
}
func (m *UpdateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovieRequest.Unmarshal(m, b)
}
func (m *UpdateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovieRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovieRequest.Merge(dst, src)
}
func (m *UpdateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMovieRequest.Size(m)
}
func (m *UpdateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovieRequest proto.InternalMessageInfo

func (m *UpdateMovieRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateMovieRequest) GetDirector() []*Director {
	if m != nil {
		return m.Director
	}
	return nil
}

func (m *UpdateMovieRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *UpdateMovieRequest) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

type UpdateMovieResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMovieResponse) Reset()         { *m = UpdateMovieResponse{} }
func (m *UpdateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMovieResponse) ProtoMessage()    {}
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{10}
}
func (m *UpdateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovieResponse.Unmarshal(m, b)
}
func (m *UpdateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovieResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovieResponse.Merge(dst, src)
}
func (m *UpdateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMovieResponse.Size(m)
}
func (m *UpdateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovieResponse proto.InternalMessageInfo

func (m *UpdateMovieResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_a891fd8c99ce3329, []int{11}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetMoviesResponse)(nil), "pb.GetMoviesResponse")
	proto.RegisterType((*Movie)(nil), "pb.Movie")
	proto.RegisterType((*Director)(nil), "pb.Director")
	proto.RegisterType((*GetMovieByIdRequest)(nil), "pb.GetMovieByIdRequest")
	proto.RegisterType((*GetMovieByIdResponse)(nil), "pb.GetMovieByIdResponse")
	proto.RegisterType((*NewMovieRequest)(nil), "pb.NewMovieRequest")
	proto.RegisterType((*NewMovieResponse)(nil), "pb.NewMovieResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "pb.DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResponse)(nil), "pb.DeleteMovieResponse")
	proto.RegisterType((*UpdateMovieRequest)(nil), "pb.UpdateMovieRequest")
	proto.RegisterType((*UpdateMovieResponse)(nil), "pb.UpdateMovieResponse")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Movies service

type MoviesClient interface {
	GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMoviesResponse, error)
	GetMovieById(ctx context.Context, in *GetMovieByIdRequest, opts ...grpc.CallOption) (*GetMovieByIdResponse, error)
	NewMovie(ctx context.Context, in *NewMovieRequest, opts ...grpc.CallOption) (*NewMovieResponse, error)
	DeleteMovie(ctx context.Context, in *DeleteMovieRequest, opts ...grpc.CallOption) (*DeleteMovieResponse, error)
	UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error)
}

type moviesClient struct {
	cc *grpc.ClientConn
}

func NewMoviesClient(cc *grpc.ClientConn) MoviesClient {
	return &moviesClient{cc}
}

func (c *moviesClient) GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMoviesResponse, error) {
	out := new(GetMoviesResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/GetMovies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) GetMovieById(ctx context.Context, in *GetMovieByIdRequest, opts ...grpc.CallOption) (*GetMovieByIdResponse, error) {
	out := new(GetMovieByIdResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/GetMovieById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) NewMovie(ctx context.Context, in *NewMovieRequest, opts ...grpc.CallOption) (*NewMovieResponse, error) {
	out := new(NewMovieResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/NewMovie", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) DeleteMovie(ctx context.Context, in *DeleteMovieRequest, opts ...grpc.CallOption) (*DeleteMovieResponse, error) {
	out := new(DeleteMovieResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/DeleteMovie", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error) {
	out := new(UpdateMovieResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/UpdateMovie", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Movies service

type MoviesServer interface {
	GetMovies(context.Context, *Empty) (*GetMoviesResponse, error)
	GetMovieById(context.Context, *GetMovieByIdRequest) (*GetMovieByIdResponse, error)
	NewMovie(context.Context, *NewMovieRequest) (*NewMovieResponse, error)
	DeleteMovie(context.Context, *DeleteMovieRequest) (*DeleteMovieResponse, error)
	UpdateMovie(context.Context, *UpdateMovieRequest) (*UpdateMovieResponse, error)
}

func RegisterMoviesServer(s *grpc.Server, srv MoviesServer) {
	s.RegisterService(&_Movies_serviceDesc, srv)
}

func _Movies_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).GetMovies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_GetMovieById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).GetMovieById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/GetMovieById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).GetMovieById(ctx, req.(*GetMovieByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_NewMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).NewMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/NewMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).NewMovie(ctx, req.(*NewMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_DeleteMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).DeleteMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/DeleteMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).DeleteMovie(ctx, req.(*DeleteMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_UpdateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).UpdateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/UpdateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).UpdateMovie(ctx, req.(*UpdateMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Movies_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Movies",
	HandlerType: (*MoviesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovies",
			Handler:    _Movies_GetMovies_Handler,
		},
		{
			MethodName: "GetMovieById",
			Handler:    _Movies_GetMovieById_Handler,
		},
		{
			MethodName: "NewMovie",
			Handler:    _Movies_NewMovie_Handler,
		},
		{
			MethodName: "DeleteMovie",
			Handler:    _Movies_DeleteMovie_Handler,
		},
		{
			MethodName: "UpdateMovie",
			Handler:    _Movies_UpdateMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movies.proto",
}

func init() { proto.RegisterFile("movies.proto", fileDescriptor_movies_a891fd8c99ce3329) }

var fileDescriptor_movies_a891fd8c99ce3329 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xde, 0xa4, 0x4d, 0xb7, 0x9d, 0x56, 0xb0, 0x4c, 0x0b, 0x6b, 0x45, 0x48, 0x5b, 0x2c, 0x7e,
	0x7a, 0x4a, 0xa5, 0x82, 0x04, 0x47, 0x04, 0x8b, 0x60, 0x0f, 0x70, 0x88, 0xe0, 0x01, 0x9a, 0xcd,
	0xb0, 0x8a, 0xd4, 0xd6, 0x21, 0x71, 0x41, 0x3d, 0xf3, 0x0e, 0x5c, 0x78, 0x14, 0x5e, 0x0e, 0xc5,
	0x76, 0xdc, 0xfc, 0xb4, 0xc0, 0x89, 0x9b, 0x3d, 0xf3, 0xf9, 0xf3, 0xcc, 0xf7, 0xcd, 0xc0, 0x68,
	0x2d, 0xbe, 0x26, 0x94, 0x07, 0x69, 0x26, 0xa4, 0x40, 0x37, 0x8d, 0xfc, 0x8b, 0x1b, 0x21, 0x6e,
	0x56, 0x34, 0x57, 0x91, 0x68, 0xfb, 0x79, 0x2e, 0x93, 0x35, 0xe5, 0x72, 0xb9, 0x4e, 0x35, 0x88,
	0xbf, 0x83, 0x3b, 0x6f, 0x49, 0xbe, 0x57, 0xef, 0x42, 0xca, 0x53, 0xb1, 0xc9, 0x09, 0x1f, 0x40,
	0x4f, 0x33, 0x31, 0x67, 0xda, 0x99, 0x0d, 0x17, 0x83, 0x20, 0x8d, 0x02, 0x85, 0x09, 0x4d, 0x02,
	0xcf, 0xa0, 0x43, 0x59, 0xc6, 0xdc, 0xa9, 0x33, 0x1b, 0x84, 0xc5, 0x91, 0xff, 0x74, 0xc1, 0x53,
	0x18, 0xbc, 0x05, 0x6e, 0x12, 0x33, 0x47, 0xa5, 0xdc, 0x24, 0xc6, 0x09, 0x78, 0x32, 0x91, 0x2b,
	0x32, 0x68, 0x7d, 0xc1, 0x19, 0xf4, 0xe3, 0x24, 0xa3, 0x6b, 0x29, 0x32, 0xd6, 0x51, 0xdf, 0x8c,
	0x8a, 0x6f, 0x2e, 0x4d, 0x2c, 0xb4, 0x59, 0x44, 0xe8, 0xee, 0x68, 0x99, 0xb1, 0xae, 0x7a, 0xae,
	0xce, 0x78, 0x1f, 0x06, 0xd7, 0x19, 0x2d, 0x25, 0xc5, 0xd1, 0x8e, 0x79, 0x2a, 0xb1, 0x0f, 0xe0,
	0x0b, 0x9b, 0x15, 0x1b, 0xd6, 0x9b, 0x3a, 0xb3, 0xe1, 0xc2, 0x0f, 0xb4, 0x14, 0x41, 0x29, 0x45,
	0xf0, 0xb1, 0x94, 0x22, 0xdc, 0x83, 0x0b, 0xde, 0x6d, 0x1a, 0x1b, 0xde, 0x53, 0xcd, 0x6b, 0x03,
	0x05, 0xaf, 0xb9, 0x88, 0x0d, 0xeb, 0xff, 0x9d, 0xd7, 0x82, 0xf9, 0x63, 0xe8, 0x97, 0x9d, 0xa1,
	0x5f, 0xe9, 0x5c, 0xab, 0x64, 0xef, 0xfc, 0x11, 0x8c, 0x4b, 0x3f, 0x5e, 0xed, 0xae, 0xe2, 0x90,
	0xbe, 0x6c, 0x29, 0x97, 0x4d, 0x49, 0xf9, 0x15, 0x4c, 0xea, 0x30, 0xe3, 0xdc, 0x05, 0x78, 0xca,
	0x20, 0x05, 0xad, 0x19, 0xa7, 0xe3, 0x07, 0x7c, 0xfb, 0xee, 0xc0, 0xed, 0x0f, 0xf4, 0x4d, 0xa3,
	0xcc, 0x77, 0xd6, 0x31, 0xe7, 0x98, 0x63, 0xee, 0x3f, 0x39, 0xd6, 0x39, 0xe6, 0x58, 0xb7, 0xe1,
	0x18, 0x7f, 0x06, 0x67, 0xfb, 0x22, 0x4c, 0x33, 0xcd, 0x39, 0x6a, 0xd7, 0xfe, 0x10, 0xf0, 0x92,
	0x56, 0x24, 0xa9, 0x56, 0x7d, 0x53, 0xac, 0x27, 0x30, 0xae, 0xa1, 0x0c, 0xbd, 0xa1, 0x73, 0xf6,
	0x74, 0x3f, 0x1c, 0xc0, 0x4f, 0xca, 0xb2, 0x3f, 0xf1, 0xfd, 0xff, 0x79, 0x2e, 0x3a, 0xa8, 0xd5,
	0x75, 0xb4, 0x83, 0x53, 0xf0, 0xde, 0xac, 0x53, 0xb9, 0x5b, 0xfc, 0x72, 0xa1, 0xa7, 0xb7, 0x1a,
	0xe7, 0x30, 0xb0, 0x2b, 0x8e, 0x6a, 0x22, 0x14, 0xc4, 0xbf, 0x5b, 0x1c, 0x5b, 0xcb, 0xcf, 0x4f,
	0xf0, 0x35, 0x8c, 0xaa, 0xc3, 0x85, 0xe7, 0x55, 0x60, 0x65, 0x2a, 0x7d, 0xd6, 0x4e, 0x58, 0x92,
	0xe7, 0xd0, 0x2f, 0x0d, 0xc5, 0x71, 0x81, 0x6b, 0xcc, 0x98, 0x3f, 0xa9, 0x07, 0xed, 0xc3, 0x97,
	0x30, 0xac, 0xb8, 0x85, 0xf7, 0x94, 0x88, 0x2d, 0x93, 0xfd, 0xf3, 0x56, 0xbc, 0xca, 0x50, 0x51,
	0x4b, 0x33, 0xb4, 0x6d, 0xd5, 0x0c, 0x07, 0x64, 0xe5, 0x27, 0x51, 0x4f, 0x2d, 0xf3, 0xd3, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xf7, 0x28, 0xd3, 0x51, 0x05, 0x00, 0x00,
}
